### ISSUE TITLE
CLD DetectorModel with LAr Calorimeter: CLD_o4_v01 (5?)

### ISSUE THREAD

**Issue by andresailer** [key4hep/k4geo#269]
* Create a CLD Detector model based on the detector model to be created in #268 where the ECal Barrel (initially) is replaced by a LAr calorimeter, using the driver from https://github.com/HEP-FCC/FCCDetectors/blob/main/Detector/DetFCChhECalInclined/src/ECalBarrelInclined_geo.cpp

**Comment by SwathiSasikumar** [comment]
A new pull request opened in k4geo by adding ```FCCee_o3_v06``` with CLD detector model along with LAr as calorimeter: https://github.com/key4hep/k4geo/pull/270.  All the steering xml files and driver from  https://github.com/HEP-FCC/FCCDetectors/blob/main/Detector/DetFCChhECalInclined/src/ECalBarrelInclined_geo.cpp are included

**Comment by Zehvogel** [comment]
I think this can be closed as the model was merged already?

**Comment by jmcarcell** [comment]
> I think this can be closed as the model was merged already?

I think so too, closing.
