### ISSUE TITLE
Bug in Geant4 shape 'generic trapezoid'

### ISSUE THREAD

**Issue by atolosadelgado** [key4hep/k4geo#321]
Hi,

Geant4 reported [yesterday](https://indico.cern.ch/event/1366947/contributions/5805315/attachments/2801780/4888123/Geant4TechnicalForum_ATLAS.pdf#page=6) a bug related to a shape called 'generic trapezoid'. They are working on it, but it may take some time to be fixed.

I took a quick look to the k4geo repo and I think we are not using it, but I preferred to leave the comment here just in case someone  was thinking about using it or if someone else wanted to crosscheck.

Best,
Alvaro

**Comment by atolosadelgado** [comment]
@jmcarcell Lorenzo Pezzoti implemented the DRD endcap [using the generic trapezoid](https://indico.cern.ch/event/1439207/contributions/6056623/attachments/2903299/5092292/lopezzot_fccsim_2472024.pdf#page=7). The shape had a bug which was fixed few weeks ago and included in the recent Geant4 beta release. Is key4hep using the Geant4 beta release?

**Comment by jmcarcell** [comment]
No

**Comment by atolosadelgado** [comment]
Patches fixing the Geant4 issues have been added to key4hep nightlies 5th of August. Twisted tube navigation problem seems to be fixed. Closing issue.
