### ISSUE TITLE
CI failed with nightlies

### ISSUE THREAD

**Issue by atolosadelgado** [key4hep/k4geo#352]
Hi,

I noticed that CI failed with nightlies:
https://github.com/key4hep/k4geo/actions/runs/9834053300/job/27145226265

Shall we report to DD4hep? There have been some changes lately that may be related to this, such as https://github.com/AIDASoft/DD4hep/pull/1288

**Comment by jmcarcell** [comment]
Yes, it should be reported there. It certainly looks like it was https://github.com/AIDASoft/DD4hep/pull/1288 since the day before it works fine and the day after it doesn't, and the only other PR merged that day is https://github.com/AIDASoft/DD4hep/pull/1289 which isn't used in k4geo.

**Comment by andresailer** [comment]
Fixed.
