### ISSUE TITLE
t_test_CLIC_o3_v14_reco_conformal failing

### ISSUE THREAD

**Issue by BrieucF** [key4hep/k4geo#364]
With today's nightlies, the t_test_CLIC_o3_v14_reco_conformal test from downstream build is failing: https://github.com/key4hep/k4geo/actions/runs/10175926863/job/28144262403?pr=346

**Comment by andresailer** [comment]
Pretty sure this is spurious

> [ VERBOSE "MyDDMarlinPandora"] PhotonReconstructionAlgorithm::CreatePhotons: StatusCodeException caught during fragmentation process.

Rerunning failed jobs

Should fix the random seed to something that works

**Comment by BrieucF** [comment]
Indeed, it has worked with second trial
