### ISSUE TITLE
Subtle mismatch in gen particles after ddsim with CLICdp and CLD in Key4HEP

### ISSUE THREAD

**Issue by jpata** [key4hep/k4geo#399]
Hi, first, thank you for your work on the nice Key4HEP software!
I hope this is the right place to open this issue, but if not, please redirect me.

I've noticed that when running CLICdp or CLD full simulation through Key4HEP, there are subtle mismatches between the particles in Pythia at the HEPMC level, especially relevant for status=1 particles.
There are two slightly separate but possibly connected issues: momentum mismatch, and daughter indices mismatch.

Please let me know if I'm doing something wrong or stumbling across a known issue.

## Momentum mismatch
The momentum components of status=1 particles between Pythia and ddsim outputs do not match exactly. The differences are largest for px, smaller for py,pz, and negligible (<1e-6) for mass. The PDGs match exactly, also by order.
<img width="551" alt="image" src="https://github.com/user-attachments/assets/9a2abbfd-f685-4a14-b745-3150528749aa">

## Daughter indices mismatch
At pythia level, from the job logs, daughter indices of tau leptons are meaningful:
<img width="741" alt="Screenshot 2024-09-27 at 21 41 28" src="https://github.com/user-attachments/assets/d178ab55-e013-4463-b198-823bf96b205f">

However, after ddsim, the daughter indices of the taus are incorrect.
<img width="765" alt="Screenshot 2024-09-27 at 21 41 57" src="https://github.com/user-attachments/assets/949e1d66-7fd8-41cc-9404-b968f0bdb44b">

## Details to reproduce

Pythia config
```
Random:setSeed = on
Main:numberOfEvents = 100         ! number of events to generate
Main:timesAllowErrors = 5          ! how many aborts before run stops

! 2) Settings related to output in init(), next() and stat().
Init:showChangedSettings = on      ! list changed settings
Init:showChangedParticleData = off ! list changed particle data
Next:numberCount = 100             ! print message every n events
Next:numberShowInfo = 1            ! print event information n times
Next:numberShowProcess = 1         ! print process record n times
Next:numberShowEvent = 100           ! print event record n times

Beams:idA = 11                     ! first beam, e+ = 11
Beams:idB = -11                    ! second beam, e- = -11

Beams:eCM = 380                    ! CM energy of collision

PartonLevel:ISR = on               ! initial-state radiation
PartonLevel:FSR = on               ! final-state radiation

! Hard process: ff -> Z/gamma
WeakSingleBoson:ffbar2gmZ = on

! Z to tau decays
23:onMode   = off
23:onIfAny  = 15
```

Steps to reproduce, with [clic_steer.py](https://github.com/HEP-KBFI/ml-tau-reco/blob/main/sim/clic_steer.py):
```bash
echo > card.cmd << EOF
Random:setSeed = on
Main:numberOfEvents = 100         ! number of events to generate
Main:timesAllowErrors = 5          ! how many aborts before run stops

! 2) Settings related to output in init(), next() and stat().
Init:showChangedSettings = on      ! list changed settings
Init:showChangedParticleData = off ! list changed particle data
Next:numberCount = 100             ! print message every n events
Next:numberShowInfo = 1            ! print event information n times
Next:numberShowProcess = 1         ! print process record n times
Next:numberShowEvent = 100           ! print event record n times

Beams:idA = 11                     ! first beam, e+ = 11
Beams:idB = -11                    ! second beam, e- = -11

Beams:eCM = 380                    ! CM energy of collision

PartonLevel:ISR = on               ! initial-state radiation
PartonLevel:FSR = on               ! final-state radiation

! Hard process: ff -> Z/gamma
WeakSingleBoson:ffbar2gmZ = on

! Z to tau decays
23:onMode   = off
23:onIfAny  = 15
EOF
wget https://raw.githubusercontent.com/HEP-KBFI/ml-tau-reco/refs/heads/main/sim/pythia.py
wget https://raw.githubusercontent.com/HEP-KBFI/ml-tau-reco/refs/heads/main/sim/clic_steer.py
source /cvmfs/sw.hsf.org/spackages6/key4hep-stack/2023-01-15/x86_64-centos7-gcc11.2.0-opt/csapx/setup.sh

echo "Random:seed=400001" >> card.cmd

k4run pythia.py -n 1 --Dumper.Filename out.hepmc --Pythia8.PythiaInterface.pythiacard card.cmd

ddsim --compactFile $LCGEO/CLIC/compact/CLIC_o3_v14/CLIC_o3_v14.xml \
      --outputFile out_sim_edm4hep.root \
      --steeringFile clic_steer.py \
      --inputFiles out.hepmc \
      --numberOfEvents 1\
      --random.seed 400001
```
 - OS version: Linux manivald 5.13.13-1.el7.elrepo.x86_64 #1 SMP Wed Aug 25 18:38:37 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Compiler version: did not compile software
 - Package version: /cvmfs/sw.hsf.org/spackages6/key4hep-stack/2023-01-15/x86_64-centos7-gcc11.2.0-opt/csapx/setup.sh or /cvmfs/sw.hsf.org/spackages7/key4hep-stack/2023-04-08/x86_64-centos7-gcc11.2.0-opt/urwcv/setup.sh
 - Input: https://github.com/HEP-KBFI/ml-tau-reco/blob/main/sim/clic_steer.py
```

**Comment by danieljeans** [comment]
I guess that the momentum mismatch is due to the crossing angle of the accelerator:
the event is boosted in x to move the event from the CM frame (usually assumed by generator) and the lab/detector frame. 

For the daughter ID's, I don't know.

**Comment by danieljeans** [comment]
For the extra photons, are they FSR from the tau? or bremsstrahlung? you could check the photons' parent (although that may be affected by the same feature), and their production vertex.

**Comment by andresailer** [comment]
I cannot reproduce this
```
k4run pythia.py -n 1 --Dumper.Filename out.hepmc --Pythia8.PythiaInterface.pythiacard card.cmd

Traceback (most recent call last):
  File "/cvmfs/sw.hsf.org/spackages6/k4fwcore/1.0pre16/x86_64-centos7-gcc11.2.0-opt/g4uz5/bin/k4run", line 34, in <module>
    exec(open(f).read())
FileNotFoundError: [Errno 2] No such file or directory: 'pythia.py'
```

**Comment by jpata** [comment]
Sorry, I forgot to put links to the pythia steering file: https://github.com/HEP-KBFI/ml-tau-reco/blob/main/sim/pythia.py

**Comment by andresailer** [comment]
The raw daughtes_begin, daughters_end seems is not that easy to parse, you actually have to redirect through the `MCParticles#1.index` branch to figure out which parent/daughters are there.
```
root [4] events->Scan("MCParticles#1.index")
***********************************
*    Row   * Instance * MCParticl *
***********************************
[snip]
*        0 *       20 *        21 *
*        0 *       21 *        22 *
*        0 *       22 *        23 *

```
[20, 23) corresponds to 21 22, 23

So rather use podio-dump to print out the collection content
```
podio-dump -d out_sim_edm4hep.root
```
```
    10000018          +15           +2   +402653184 -1.000000e+00 +0.000000e+00 +1.776820e+00 +0.000000e+00 +0.000000e+00 +0.000000e+00  -1.229446e+00 -2.529469e+00 -1.862593e+01  -1.132067e+01 -2.328736e+01 -1.714836e+02  -1.131764e+01 -2.328884e+01 -1.714836e+02  +0.0\
00000e+00 +0.000000e+00 +0.000000e+00            +0 +0
      parents : 10000016
      daughters : 10000021 10000022 10000023
```

Or more conveniently, `ddsim -O out.slcio` and then `dumpevent out.slcio 1`, which has better formatting at the moment.

```
[   id   ]index|      PDG |    px,     py,        pz    | px_ep,   py_ep , pz_ep      | energy  |gen|[simstat ]| vertex x,     y   ,   z     | endpoint x,    y  ,   z     |    mass |  charge |            spin             | colorflow | [parents] - [daughters]
[snip]
[00000048]   16|        15|-1.13e+01,-2.33e+01,-1.71e+02| 0.00e+00, 0.00e+00, 0.00e+00| 1.73e+02| 23 |[  v     ]|-1.27e-01,-7.84e-01,-1.98e+01|-1.29e-01,-7.84e-01,-1.98e+01| 1.78e+00|-1.00e+00| 0.00e+00, 0.00e+00, 0.00e+00|  (0, 0)   | [15] - [18]
[00000049]   17|       -15| 1.30e+01, 2.16e+01,-7.85e+00| 0.00e+00, 0.00e+00, 0.00e+00| 2.64e+01| 23 |[  v     ]|-1.27e-01,-7.84e-01,-1.98e+01|-1.29e-01,-7.84e-01,-1.98e+01| 1.78e+00| 1.00e+00| 0.00e+00, 0.00e+00, 0.00e+00|  (0, 0)   | [15] - [19,20]
[00000050]   18|        15|-1.13e+01,-2.33e+01,-1.71e+02|-1.13e+01,-2.33e+01,-1.71e+02| 1.73e+02| 2 |[  vt    ]| 0.00e+00, 0.00e+00, 0.00e+00|-1.23e+00,-2.53e+00,-1.86e+01| 1.78e+00|-1.00e+00| 0.00e+00, 0.00e+00, 0.00e+00|  (0, 0)   | [16] - [21,22,23]
[00000051]   19|       -15| 1.30e+01, 2.16e+01,-7.85e+00| 1.30e+01, 2.16e+01,-7.85e+00| 2.64e+01| 2 |[  vt    ]| 0.00e+00, 0.00e+00, 0.00e+00| 1.28e-01, 2.12e-01,-7.73e-02| 1.78e+00| 1.00e+00| 0.00e+00, 0.00e+00, 0.00e+00|  (0, 0)   | [17] - [24,25,26,27]
[00000052]   20|        22| 8.90e-06, 1.14e-08, 4.72e-06| 0.00e+00, 0.00e+00, 0.00e+00| 1.01e-05| 1 |[  vt  s ]| 0.00e+00, 0.00e+00, 0.00e+00| 4.41e+01, 5.63e-02, 2.34e+01| 0.00e+00| 0.00e+00| 0.00e+00, 0.00e+00, 0.00e+00|  (0, 0)   | [17] - []
[00000053]   21|        16|-4.73e+00,-8.88e+00,-7.08e+01|-4.73e+00,-8.88e+00,-7.08e+01| 7.15e+01| 1 |[     l  ]|-1.23e+00,-2.53e+00,-1.86e+01|-2.01e+03,-3.76e+03,-3.00e+04| 0.00e+00| 0.00e+00| 0.00e+00, 0.00e+00, 0.00e+00|  (0, 0)   | [18] - []
[00000054]   22|        11|-1.53e+00,-3.54e+00,-2.26e+01| 0.00e+00,-0.00e+00, 0.00e+00| 2.29e+01| 1 |[    c s ]|-1.23e+00,-2.53e+00,-1.86e+01|-1.42e+02,-4.20e+02,-2.60e+03| 5.11e-04|-1.00e+00| 0.00e+00, 0.00e+00, 0.00e+00|  (0, 0)   | [18] - [35,36,37,38]
```

The photon is just the Final State Radiation photon from the Tau and was there also in the HepMC record

The momentum mismatch is, as Daniel, said from the crossing-angle Lorentz boost.

**Comment by jpata** [comment]
Thank you for the clarifications! Then I close this issue, as the problem was between the keyboard and the chair :)

**Comment by andresailer** [comment]
Thanks @tmadlener for the further clarification. But really podio-dump should be preferred over raw tree parsing.

And @jpata This was a subtle issue! Don't hesitate to ask again if something seems odd!

By the way,  have a look at the first post and what I did to the "reproducer", which now is a signle copy and paste away from being run, which makes it easy to reproduce and check for missing files or typos.
